# filepath: e:\git-repos\lending-api\docker-compose.yml
version: "3.8"

services:
    api:
        build: .
        container_name: wallet-analysis-api
        ports:
            - "8000:8000"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
            - GEMINI_API_KEY=${GEMINI_API_KEY}
            - HOST=0.0.0.0
            - PORT=8000
        depends_on:
            - db
        volumes:
            - .:/app
        restart: unless-stopped

    db:
        image: postgres:14
        container_name: wallet-analysis-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data:
