name: CI CD Pipeline - Production

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    SERVER_HOST: ${{ secrets.SERVER_HOST }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
    DOCKER_REPOSITORY_NAME: ${{ secrets.DOCKER_REPOSITORY_NAME }}
    DOCKER_TAG: ${{ secrets.DOCKER_TAG }}
    DOCKER_RUNNING_PORT: ${{ secrets.DOCKER_RUNNING_PORT }}
    GITHUB_RUN_NUMBER: ${{ github.run_number }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Custom Registry
              uses: docker/login-action@v2
              with:
                registry: mekleren.azurecr.io
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ env.DOCKER_PAT }}
              with:
                  username: ${{ env.DOCKER_USERNAME }}
                  password: ${{ env.DOCKER_PAT }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  platforms: linux/amd64
                  push: true
                  tags: |
                      ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY_NAME }}:${{ env.DOCKER_TAG }}
                      ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY_NAME }}:${{ env.DOCKER_TAG }}-${{ env.GITHUB_RUN_NUMBER }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Server via SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ env.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
                  ssh -v -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << EOF
                    docker pull ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY_NAME }}:${{ env.DOCKER_TAG }}
                    docker stop binus-${{ env.DOCKER_REPOSITORY_NAME }} || true
                    docker rm itb-${{ env.DOCKER_REPOSITORY_NAME }} || true
                    docker run -d --env-file .lending-api.env --add-host=host.docker.internal:172.17.0.1 --name ${{ env.DOCKER_REPOSITORY_NAME }} -p ${{ env.DOCKER_RUNNING_PORT }}:8000 ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY_NAME }}:${{ env.DOCKER_TAG }}
                  EOF
